import argparse
import os
import re
import sys
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import Script
from alembic.util import CommandError

# Import all models so every table/column is registered on Base.metadata
# before autogenerate compares it against the database.
from app.database import Base
import app.models  # noqa: F401

BACKEND_DIR = Path(__file__).resolve().parent

# Reference schema for tenant-scope autogenerate: tenant_individual is created
# and migrated to head automatically (app/services/tenant.py), so it reflects
# what every tenant schema looks like.
DEFAULT_TENANT_SCHEMA = "tenant_individual"

PUBLIC_GUARD = (
    "    # Public-schema revision: no-op when a tenant schema replays the chain.\n"
    '    if os.getenv("IS_TENANT_MIGRATION") == "true":\n'
    "        return\n"
    "\n"
)
TENANT_GUARD = (
    "    # Tenant-schema revision: no-op during the public-schema upgrade.\n"
    '    if os.getenv("IS_TENANT_MIGRATION") != "true":\n'
    "        return\n"
    "\n"
)


def make_config() -> Config:
    cfg = Config(str(BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    # env.py drops autogenerated revisions whose upgrade ops are empty.
    cfg.attributes["skip_empty_autogenerate"] = True
    return cfg


def set_scope_env(tenant: bool, tenant_schema: str) -> None:
    # env.py's include_object splits tables by schema: public-schema tables
    # migrate when IS_TENANT_MIGRATION is unset/false, tenant tables when true.
    os.environ["IS_TENANT_MIGRATION"] = "true" if tenant else "false"
    if tenant:
        # Point env.py's search_path at a real migrated tenant schema so
        # autogenerate diffs the models against tenant tables, not public.
        os.environ["IS_TENANT_MIGRATION_SCHEMA"] = tenant_schema
    else:
        os.environ.pop("IS_TENANT_MIGRATION_SCHEMA", None)


def inject_scope_guard(path: str, tenant: bool) -> None:
    """Make the generated revision a no-op outside its scope, matching the
    convention of the hand-written migrations (e.g. 38e248fd43cb)."""
    source = Path(path).read_text(encoding="utf-8")
    if not re.search(r"^import os$", source, flags=re.M):
        source = source.replace(
            "import sqlalchemy as sa\n", "import sqlalchemy as sa\nimport os\n", 1
        )
    guard = TENANT_GUARD if tenant else PUBLIC_GUARD
    source = re.sub(
        r"(def (?:upgrade|downgrade)\(\) -> None:\n)", r"\1" + guard, source
    )
    Path(path).write_text(source, encoding="utf-8")


def generate(cfg: Config, message: str, tenant: bool, tenant_schema: str) -> list[Script]:
    set_scope_env(tenant, tenant_schema)
    scope = "tenant" if tenant else "public"
    print(f"Generating {scope}-schema migration: {message}")
    result = command.revision(cfg, autogenerate=True, message=message)
    scripts = [
        s for s in (result if isinstance(result, list) else [result])
        if isinstance(s, Script)
    ]
    if not scripts:
        print(f"  No {scope}-schema changes detected — nothing generated.")
    for script in scripts:
        inject_scope_guard(script.path, tenant)
        print(f"  Wrote {script.path}")
    return scripts


def main():
    parser = argparse.ArgumentParser(
        description="Autogenerate Alembic migrations covering all models."
    )
    parser.add_argument("-m", "--message", default="sync models", help="Revision message")
    parser.add_argument(
        "--scope",
        choices=["public", "tenant", "all"],
        default="all",
        help="Which schema's tables to include (default: all, generates both revisions)",
    )
    parser.add_argument(
        "--tenant-schema",
        default=DEFAULT_TENANT_SCHEMA,
        help="Existing migrated tenant schema to diff tenant tables against "
        f"(default: {DEFAULT_TENANT_SCHEMA})",
    )
    args = parser.parse_args()

    tables = sorted(Base.metadata.tables)
    print(f"Detected {len(tables)} tables: {', '.join(tables)}")

    cfg = make_config()
    generated: list[Script] = []
    try:
        if args.scope in ("public", "all"):
            message = f"{args.message} (public)" if args.scope == "all" else args.message
            generated += generate(cfg, message, tenant=False, tenant_schema=args.tenant_schema)

        if args.scope in ("tenant", "all"):
            if args.scope == "all" and generated:
                # The public revision moved the head, so autogenerate against the
                # tenant schema would refuse with "target database is not up to
                # date". Replay the chain on the reference schema first — the new
                # public revision is a guarded no-op there, it only stamps head.
                print(f"Upgrading {args.tenant_schema} to the new head...")
                set_scope_env(tenant=True, tenant_schema=args.tenant_schema)
                command.upgrade(cfg, "head")
            message = f"{args.message} (tenant)" if args.scope == "all" else args.message
            generated += generate(cfg, message, tenant=True, tenant_schema=args.tenant_schema)
    except CommandError as exc:
        if "not up to date" in str(exc):
            sys.exit(
                f"Error: {exc}\n"
                "Apply pending migrations first: 'alembic upgrade head' for the public "
                f"schema; for the tenant scope, ensure schema '{args.tenant_schema}' "
                "exists and is migrated to head."
            )
        raise

    if generated:
        print(
            "Review the generated revision(s), then apply with 'alembic upgrade head'. "
            "Tenant schemas pick them up via run_tenant_migrations()."
        )


if __name__ == "__main__":
    main()
