"""Add public tenant tables

Revision ID: 38e248fd43cb
Revises: f9c7ee95f633
Create Date: 2026-06-05 01:31:12.301251

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision: str = '38e248fd43cb'
down_revision: Union[str, None] = 'f9c7ee95f633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if os.getenv("IS_TENANT_MIGRATION") == "true":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_token_mappings',
    sa.Column('agent_token', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_token'),
    schema='public'
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('org_key', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_organizations_domain'), 'organizations', ['domain'], unique=True, schema='public')
    op.create_index(op.f('ix_public_organizations_org_key'), 'organizations', ['org_key'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    if os.getenv("IS_TENANT_MIGRATION") == "true":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_organizations_org_key'), table_name='organizations', schema='public')
    op.drop_index(op.f('ix_public_organizations_domain'), table_name='organizations', schema='public')
    op.drop_table('organizations', schema='public')
    op.drop_table('agent_token_mappings', schema='public')
    # ### end Alembic commands ###
